version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: >
      sh -c "./wait-for-it.sh db:5432 -- \
         python manage.py migrate && \
         python manage.py collectstatic --noinput && \
         gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    # 개발 환경
    environment:
      - NODE_ENV=production
      - BROWSER=none
    # environment:
    #   - NODE_ENV=production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/staticfiles:/app/staticfiles:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: approval_db
      POSTGRES_USER: approval_user
      POSTGRES_PASSWORD: approval_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
